emqtt1:
  image: philipz/emqtt
  container_name: emqtt1
  restart: always
  volumes:
    - "/data/emqttd/emqtt1:/emqttd"
  ports:
    - "1883:1883"
    - "8883:8883"
    - "8085:8083"
    - "18083:18083"

emqtt2:
  image: philipz/emqtt
  container_name: emqtt2
  restart: always
  volumes:
    - "/data/emqttd/emqtt2:/emqttd"
  ports:
    - "1884:1883"
    - "8884:8883"
    - "8086:8083"
    - "18084:18083"
  environment:
    MASTER: "`docker inspect --format='{{.NetworkSettings.IPAddress}}'`"
